version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - FLASK_ENV=development
      - FLASK_APP=app.py
    env_file:
      - .env

networks:
  default:
    driver: bridge