version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - Frontend.env

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI="mongodb+srv://samijaffri01:6XjmdnygdfRrD8dF@cluster0.fgfo7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - FLASK_ENV=development
      - FLASK_APP=app.py
    env_file:
      - Backend.env

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: studentdb

volumes:
  mongo_data:

networks:
  default:
    driver: bridge