name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '31 3 * * *'  # Runs daily at 3:31 AM UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      # Mark stale issues and pull requests
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been marked as stale due to inactivity. It will be closed if no further activity occurs.'
          stale-pr-message: 'This pull request has been marked as stale due to inactivity. It will be closed if no further activity occurs.'
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'

      # Update priority of inactive issues (not pull requests)
      - name: Increase Priority of Inactive Issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });

            const priorityLevels = ['priority:low', 'priority:medium', 'priority:high'];

            for (const issue of issues) {
              // Skip pull requests
              if (issue.pull_request) continue;

              const lastUpdated = new Date(issue.updated_at);
              const now = new Date();
              const diffTime = Math.abs(now - lastUpdated);
              const diffDays = diffTime / (1000 * 60 * 60 * 24);

              if (diffDays >= 7) {
                const currentPriority = issue.labels.find(label => priorityLevels.includes(label.name));

                if (!currentPriority) {
                  await github.rest.issues.addLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    labels: ['priority:low']
                  });
                } else {
                  const currentIndex = priorityLevels.indexOf(currentPriority.name);
                  if (currentIndex < priorityLevels.length - 1) {
                    await github.rest.issues.removeLabel({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: issue.number,
                      name: currentPriority.name
                    });
                    await github.rest.issues.addLabels({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: issue.number,
                      labels: [priorityLevels[currentIndex + 1]]
                    });
                  }
                }
              }
            }

      # Close inactive pull requests after a week of inactivity
      - name: Close Inactive Pull Requests
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });

            const now = new Date();
            for (const pr of pullRequests) {
              const lastUpdated = new Date(pr.updated_at);
              const diffTime = Math.abs(now - lastUpdated);
              const diffDays = diffTime / (1000 * 60 * 60 * 24);

              if (diffDays >= 7) {
                await github.rest.pulls.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                  state: 'closed',
                });
              }
            }
